### ISSUE TITLE
Implement rate limiting in IAM source

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/aws-source#186]
Currently the IAM source doesn't do any rate limiting, also due to the nature if the API it needs to do a large number of queries. We should do some research around the rate limits for the IAM API and implement them here.

**Comment by DavidS-om** [comment]
Could this be the reason for https://github.com/overmindtech/aws-source/issues/166 ?

**Comment by dylanratcliffe** [comment]
I don't think so, it's not raising any errors. Though I haven't tested what the library does when rate limited so possibly
