### ISSUE TITLE
DynamoDB.DescribeTable error: "validation error(s) found. missing required field, DescribeTableInput.TableName" input="<nil>"

### ISSUE THREAD

**Issue by DavidS-ovm** [overmindtech/aws-source#496]
> time="2024-05-17T09:39:46Z" level=error msg="Error running Get for List item" error="operation error DynamoDB: DescribeTable, 1 validation error(s) found.\n- missing required field, DescribeTableInput.TableName.\n" input="<nil>" scope=1234567890.us-east-1

**Comment by dylanratcliffe** [comment]
@DavidS-ovm Where did this error come from? I'm going to add an additional check to the source but I'm skeptical that's the issue. I see that the account is `1234567890 ` is this just obfuscated or has this come from some kind of test?

**Comment by DavidS-ovm** [comment]
> @DavidS-ovm Where did this error come from? I'm going to add an additional check to the source but I'm skeptical that's the issue. I see that the account is `1234567890 ` is this just obfuscated or has this come from some kind of test?


yes, the account id is obfuscated. Here's the relevant log query: https://ui.honeycomb.io/overmind/environments/prod/datasets/kubernetes-metrics/result/qBq1wJmF9qx?hideCompare
